# -*- coding: utf-8 -*-
"""Introdução_teste_software 21.02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-OnJPOCvZy5HPTk8rUUw9EAPpILD6jl
"""

AULAS TIPOS TESTES

TESTES UNITARIOS

def soma(a,b):
  return a+b

def test_soma():
  assert soma(2,3)== 5
  assert soma(-2,3) == 1
  assert soma(-2,-3) == -5
  assert soma(0,0) == 0
  print("Teste unitario Passou!!")
  test_soma()

"""Teste de Interação

"""

#Modulo de Autenticação

def login (usuario,senha):
  if usuario == "admin" and  senha == "1234":
    return "Login bem sucedido"
    return "Falha no login"

#Modulo de Autenticação

def acessar_sistema(usuario,senha):
  mensagem = login,(usuario,senha)
  if mensagem == "Login bem sucedido":
    return("Acesso Autorizado")
  return "Acesso negado"

#Teste de Integração

def test_acesso_sistema ():
  assert acessar_sistema("admin","1234") == "Acesso Autorizado"
  assert acessar_sistema("admin","4321") == "Acesso negado"
  print ("Teste de Integração Passou!")
  test_acesso_sistema ()

"""Teste de Sistema"""

#Sistema de Carrinho de Compras

class CarinhoDeComprar:
  def __init__(self):
    self.Itens = []

  def adicionar_item(self,item):
    self.Itens.append(item)

  def total_itens(self):
      return len(self.itens)

  def test_sistema():
    carrinho = CarrinhoDeCompras()
    carrinho.adicionar_item("Produto1")
    carrinho.adicionar_item("Produto2")
    assert carrinho.total_itens() == 2
    print ("Teste de Sistema Passou!")

    test_sistema()

"""Teste de Aceitação"""

def test_aceitacao():
  resultado = acessar_sistema("admin","1234")
  assert resultado == "Acesso Autorizado"
  print("Teste de Aceitação Passou!")
  test_aceitacao()

"""Teste de Regresão"""

def test_regressao():
  assert soma(10,20) == 30
  print("Teste de Regressão Passou!")
  test_regressao()

"""Teste Exploratorio"""